import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNavWrapper from "./ui/sidenav/sidenavWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ПослеЧек",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            try {
              const stored = localStorage.getItem("theme");
              const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
              const theme = stored || (systemDark ? "dark" : "light");

              if (theme === "dark") {
                document.documentElement.classList.add("dark");
              } else {
                document.documentElement.classList.remove("dark");
              }
            } catch (e) {}
          `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col md:grid md:grid-cols-[220_auto] gap-3 p-4 bg-bg-primary text-text-primary">
        <div className="fixed z-50 md:static bottom-0 md:bottom-auto md:left-auto left-0 w-full md:w-auto md:grid md:grid-rows-[100_auto] gap-3 md:col-[1/2]">
          <h1 className="hidden p-4 h-(--header-height) rounded-md text-4xl md:flex justify-center items-center bg-accent text-primary shadow-sm border border-border">ПослеЧек</h1>
          <SideNavWrapper />
        </div>
        {children}
      </body>
    </html>
  );
}
