import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/sidenav/sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ПослеЧек",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="ru" className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
  <body className="min-h-full flex flex-col md:grid md:grid-cols-[220_auto] gap-3 p-4 bg-background text-foreground">
    <div className="flex flex-col md:grid md:grid-rows-[100_auto] gap-3">
      <h1 className="p-4 rounded-md text-4xl flex justify-center items-center bg-primary text-primary-foreground shadow-sm border border-border">
        ПослеЧек
      </h1>
      <SideNav />
    </div>
    {children}
  </body>
</html>
  );
}
